<?php

/**
*Implements hook_permission().
*/
function my_blocks_permission() {
  return array(
    'access my blocks' => array(
      'title'       => t('Role for my blocks'),
      'description' => t('Perfom role for my blocks'),
    ),
  );
}
/**
*Implements hook_block_info().
*/
function my_blocks_block_info() {
  $blocks = array();
  $blocks['my_first_block'] = array(
  	'info' => t('My custom block'),
  	);
  return $blocks;
}

/**
*Implements hook_block_view().
*/
function my_blocks_block_view($delta = '') {
  $block = array();
  if ($delta == 'my_first_block') {
  	$block['subject'] = t('Block subject');
  	$block['content'] = ('');
    if (user_access('content')) {
      $result = db_select('taxonomy_term_data', 't')
      ->fields('t', array('tid', 'name'))
      ->condition('vid', 2)
      ->execute()
      ->fetchAll(PDO::FETCH_ASSOC);
    
    foreach ($result as $tax) {
      $block['content'] .= '<a href="?q='. base_path() . 'janry/' .$tax['tid'] .'/' . '">' . $tax['name'] . '</a><br>';
    }
  }
  else {
    $block['subject'] = t('Block subject');
    $block['content'] = t('Not access');
  }
    
  }
  return $block;
}


?>