<?php

function my_blocks_permission() {
  return array(
    'my blocks' => array(
      'title' => t('weweweewe'),
    ),
  );
}
/**
*Implements hook_block_info().
*/
function my_blocks_block_info() {
  $blocks = array();
  $blocks['my_first_block'] = array(
  	'info' => t('My custom block'),
  	);
  return $blocks;
}

/**
*Implements hook_block_view().
*/
function my_blocks_block_view($delta = '') {
  $block = array();
  if ($delta == 'my_first_block') {
  	$block['subject'] = t('Block subject');
  	$block['content'] = ('');
  	$query = db_query('SELECT tid, name FROM {taxonomy_term_data} WHERE vid = 2')->fetchAll(PDO::FETCH_ASSOC);

  	foreach ($query as $tax) {
  		$block['content'] .= '<a href="?q='. base_path() . 'janry/' .$tax['tid'] .'/' . '">' . $tax['name'] . '</a><br>';
  	}
  }
  return $block;
}


?>