<?php


/**
 *Implements hook_menu().
 */
function my_forms_menu() {
  $items = array();
  $items['custom-contacts'] = array(
    'title'            => t('Contacts'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   =>array('my_forms_page_form'),
    'access callback'  => TRUE,
    'type'             => MENU_NORMAL_ITEM,
    'menu_name'        => 'main-menu',
    'weight'           => 10,
  );

  return $items;
}


/**
 *Define form.
 */
function my_forms_page_form($form, &$form_state) {
  $form['name'] = array(
    '#title' => t('Your name'),
    '#type' => 'textfield',
    '#description' => t('Please enter your name'),
  );
  $form['lastname'] = array(
    '#title' => t('Your lastname'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Please enter your lastname'),
  );
  $form['nickname'] = array(
    '#title' => t('Your name'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Please enter your nikname'),
  );
  $form['email'] = array(
    '#title' => t('Your e-mail'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Please enter your e-mail'),
  );
  $form['number'] = array(
    '#title' => t('Your tel. number'),
    '#type' => 'textfield',
    '#description' => t('Please enter your telephone number'),
  );
  $form['genre'] = array(
    '#title' => t('Your genre'),
    '#type' => 'radios',
    '#options' => array(t('Female'), t('Male')),
  );
  $form['country'] = array(
    '#title' => t('Your country'),
    '#type' => 'select',
    '#options' => array(t('Ukraine'), t('Russia'), t('USA')),
  );
  $form['message'] = array(
    '#title' => t('Your message'),
    '#type' => 'textarea',
    '#required' => TRUE,
  );
  $form['agree'] = array(
    '#title' => t('I agree'),
    '#type' => 'checkbox',
    '#required' => TRUE,
    '#options' => array(t('Ukraine'), t('Russia'), t('USA')),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  return $form;
}



/**
 * Validate function.
 */
function my_forms_page_form_validate($form, &$form_state) {
  if (!filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL)) {
    form_set_error($form_state['values']['email'], 'E-mail is no correct');
  }
  elseif (!filter_var($form_state['values']['number'], FILTER_VALIDATE_INT)) {
    form_set_error($form_state['values']['number'], 'The phone number is not correct');
  }
}


/**
 * Submit function/
 */
function my_forms_page_form_submit($form, &$form_state) {
  debug($form_state['values']);
}


/**
 * My submit function 
 */
function test_submit($form, &$form_state) {
drupal_set_message(t('some text'), 'error');
}


/**
 *Implements hook_form_alter().
 */
function my_forms_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['search_block_form']['#type'] = 'checkbox';
    $form['#submit'][] = 'test_submit';
  }
}
